"""new table email_team_member_history for audit trail of action performed on team members

Revision ID: 0f81d4a5efe0
Revises: e182847d89e6
Create Date: 2025-09-15 14:53:32.682953

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0f81d4a5efe0'
down_revision: Union[str, Sequence[str], None] = 'e182847d89e6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "email_team_member_history",
        sa.Column("id", sa.String(36), nullable=False),
        sa.Column("team_member_id", sa.String(36), nullable=False),
        sa.Column("team_id", sa.String(36), nullable=False),
        sa.Column("user_email", sa.String(255), nullable=False),
        sa.Column("role", sa.String(50), nullable=False, server_default=sa.text("'member'")),
        sa.Column("action", sa.String(50), nullable=False),
        sa.Column("action_by", sa.String(255), nullable=True),
        sa.Column("action_timestamp", sa.DateTime(timezone=True), nullable=False, server_default=sa.func.now()),
        sa.PrimaryKeyConstraint("id"),
        sa.ForeignKeyConstraint(["team_member_id"], ["email_team_members.id"]),
        sa.ForeignKeyConstraint(["team_id"], ["email_teams.id"]),
        sa.ForeignKeyConstraint(["user_email"], ["email_users.email"]),
        sa.ForeignKeyConstraint(["action_by"], ["email_users.email"]),
    )

    # Insert one audit entry for each unique (user_email, team_id) combination
    bind = op.get_bind()
    result = bind.execute(sa.text("""
        SELECT id, team_id, user_email, role
        FROM email_team_members
        WHERE (team_id, user_email) IN (
            SELECT team_id, user_email FROM email_team_members GROUP BY team_id, user_email
        )
    """))
    seen = set()
    import datetime
    for row in result:
        key = (row[1], row[2])  # (team_id, user_email)
        if key in seen:
            continue
        seen.add(key)
        bind.execute(
            sa.text(
                "INSERT INTO email_team_member_history (id, team_member_id, team_id, user_email, role, action, action_by, action_timestamp) "
                "VALUES (:id, :team_member_id, :team_id, :user_email, :role, :action, :action_by, :action_timestamp)"
            ),
            {
                "id": row[0],
                "team_member_id": row[0],
                "team_id": row[1],
                "user_email": row[2],
                "role": row[3],
                "action": "migrated",
                "action_by": None,
                "action_timestamp": datetime.datetime.now(),
            }
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("email_team_member_history")
    # ### end Alembic commands ###
